# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['created_time'], 'verbose_name': '\u591a\u5c42\u8bc4\u8bba', 'verbose_name_plural': '\u591a\u5c42\u8bc4\u8bba'},
        ),
    ]
