# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '\u8bc4\u8bba', 'verbose_name_plural': '\u8bc4\u8bba'},
        ),
        migrations.AddField(
            model_name='comment',
            name='user_icon',
            field=models.ImageField(default='image/default.png', upload_to='image/%Y/%m'),
        ),
    ]
