# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20180306_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='last_time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u66f4\u65b0\u65f6\u95f4'),
        ),
    ]
