# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-03 03:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20180320_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_commentset', to=settings.AUTH_USER_MODEL),
        ),
    ]
