# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-03 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180320_2322'),
        ('comments', '0004_auto_20180403_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.blog'),
        ),
    ]
