# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_icon',
            field=models.ImageField(default='image/default.png', max_length=500, upload_to='images/%Y/%m'),
        ),
    ]
