# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-04 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20180404_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='qq',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='QQ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_icon',
            field=models.ImageField(blank=True, default='image/default.png', max_length=500, null=True, upload_to='images/%Y/%m'),
        ),
    ]
