# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20180121_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='username',
            name='username',
            field=models.CharField(default=2, max_length=200, verbose_name='\u7528\u6237\u540d'),
            preserve_default=False,
        ),
    ]
