# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_username_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Username',
            new_name='User',
        ),
    ]
