# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-25 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20180404_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_icon',
            field=models.ImageField(blank=True, default='image/default.png', max_length=500, null=True, upload_to='images/%Y/%m', verbose_name='\u7528\u6237\u5934\u50cf'),
        ),
    ]
