# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-02 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_auto_20180425_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='qq',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='QQ'),
        ),
    ]
