# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-02 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0013_auto_20180502_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mobile',
            new_name='user_mobile',
        ),
    ]
