# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-02 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0014_auto_20180502_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_mobile',
            field=models.CharField(max_length=11, null=True, verbose_name='\u7535\u8bdd\u53f7\u7801'),
        ),
    ]
