# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-02 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0015_auto_20180502_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_mobile',
        ),
    ]
