# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-02 01:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20180320_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShortMessage_mobile', models.CharField(max_length=11, verbose_name='\u7535\u8bdd\u53f7\u7801')),
                ('ShortMessage_code', models.CharField(max_length=6, verbose_name='\u77ed\u4fe1\u9a8c\u8bc1\u7801')),
                ('ShortMessage_message', models.CharField(blank=True, max_length=70, null=True, verbose_name='\u77ed\u4fe1\u5185\u5bb9')),
                ('ShortMessage_created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u77ed\u4fe1\u53d1\u9001\u65f6\u95f4')),
                ('ShortMessage_type', models.CharField(choices=[('0', 'Register'), ('1', 'Forgot'), ('2', 'Modify')], max_length=1)),
                ('ShortMessage_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ShortMessage_created_time'],
                'verbose_name': '\u77ed\u4fe1',
                'verbose_name_plural': '\u77ed\u4fe1',
            },
        ),
    ]
