# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-02 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180502_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortmessage',
            name='ShortMessage_user',
        ),
    ]
